package in.dualspace.cloner.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import in.dualspace.cloner.db.CloneModel;

import in.dualspace.cloner.db.CloneModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cloneModelDaoConfig;

    private final CloneModelDao cloneModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cloneModelDaoConfig = daoConfigMap.get(CloneModelDao.class).clone();
        cloneModelDaoConfig.initIdentityScope(type);

        cloneModelDao = new CloneModelDao(cloneModelDaoConfig, this);

        registerDao(CloneModel.class, cloneModelDao);
    }
    
//    public void clear() {
//        cloneModelDaoConfig.clearIdentityScope();
//    }

    public CloneModelDao getCloneModelDao() {
        return cloneModelDao;
    }

}
