package com.polestar.domultiple.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "CLONE_MODEL".
 */
@Entity
public class CloneModel {

    @Id
    private Long id;
    private String packageName;
    private String path;
    private String name;
    private String description;
    private int index;
    private long clonedTime;
    private Boolean notificationEnable;
    private Integer lockerState;
    private Integer launched;

    @Generated(hash = 1465161905)
    public CloneModel() {
    }

    public CloneModel(Long id) {
        this.id = id;
    }

    @Generated(hash = 1295562137)
    public CloneModel(Long id, String packageName, String path, String name, String description, int index, long clonedTime, Boolean notificationEnable, Integer lockerState, Integer launched) {
        this.id = id;
        this.packageName = packageName;
        this.path = path;
        this.name = name;
        this.description = description;
        this.index = index;
        this.clonedTime = clonedTime;
        this.notificationEnable = notificationEnable;
        this.lockerState = lockerState;
        this.launched = launched;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPackageName() {
        return packageName;
    }

    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public int getIndex() {
        return index;
    }

    public void setIndex(int index) {
        this.index = index;
    }

    public long getClonedTime() {
        return clonedTime;
    }

    public void setClonedTime(long clonedTime) {
        this.clonedTime = clonedTime;
    }

    public Boolean getNotificationEnable() {
        return notificationEnable;
    }

    public void setNotificationEnable(Boolean notificationEnable) {
        this.notificationEnable = notificationEnable;
    }

    public Integer getLockerState() {
        return lockerState;
    }

    public void setLockerState(Integer lockerState) {
        this.lockerState = lockerState;
    }

    public Integer getLaunched() {
        return launched;
    }

    public void setLaunched(Integer launched) {
        this.launched = launched;
    }

}
